INSERT INTO SAMPLE VALUES('1', 'VALUE1');
INSERT INTO SAMPLE VALUES('2', 'VALUE2');

INSERT INTO DEVICE_TYPE VALUES('1', 'Windows Workstation');
INSERT INTO DEVICE_TYPE VALUES('2', 'Windows Server');
INSERT INTO DEVICE_TYPE VALUES('3', 'MAC');
INSERT INTO DEVICE_TYPE VALUES('900', 'CentOS');

INSERT INTO SERVICE_DEVICE VALUES ('1','Testing Service 1',300);
INSERT INTO SERVICE_DEVICE VALUES ('2','Testing Service 2',400);
INSERT INTO SERVICE_DEVICE VALUES ('3','Testing Service 3',500);

INSERT INTO DEVICE VALUES ('1', 'Dev Server test 1','1');
INSERT INTO DEVICE_SERVICES VALUES('1','1');
INSERT INTO DEVICE_SERVICES VALUES('1','2');
INSERT INTO DEVICE_SERVICES VALUES('1','3');